name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build amd64
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}"
        platforms: linux/amd64
        file: Dockerfile
        push: true
        tags: casraw/blablaland-frontend:${{ github.sha }},casraw/blablaland-frontend:latest
        cache-from: type=registry,ref=casraw/blablaland-frontend:latest
        cache-to: type=inline
    - name: Create SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_SERVER_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.KNOWN_HOST }}" > ~/.ssh/known_hosts
    - name: Run deploy step
      run: |
        ssh  -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "docker stop frontend ; docker rm frontend ; docker run --name frontend -v letsencrypt:/etc/letsencrypt -d -p 80:80 casraw/blablaland-frontend:${{ github.sha }}"
              

