name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build amd64
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}"
        platforms: linux/amd64
        file: Dockerfile
        push: true
        tags: casraw/casraw/blablaland-frontend:${{ github.sha }},casraw/casraw/blablaland-frontend:latest
        cache-from: type=registry,ref=casraw/casraw/blablaland-frontend:latest
        cache-to: type=inline

